"""empty message

Revision ID: 47ddc4681323
Revises: 38c4e85512a9
Create Date: 2017-08-30 14:32:58.940428

"""

# revision identifiers, used by Alembic.
revision = '47ddc4681323'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('roles',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=64), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=64), nullable=True),
    # sa.Column('username', sa.String(length=64), nullable=True),
    # sa.Column('role_id', sa.Integer(), nullable=True),
    # sa.Column('password_hash', sa.String(length=128), nullable=True),
    # sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.add_column('users',
                  sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column(
        'users',
        sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_roles_default', 'roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'confirmed')
    # op.drop_table('users')
    # op.drop_table('roles')
    # ### end Alembic commands ###
