"""add avatar_hash

Revision ID: 8a4ed31ead43
Revises: 8a33708e30ec
Create Date: 2017-09-17 12:10:57.227368

"""

# revision identifiers, used by Alembic.
revision = '8a4ed31ead43'
down_revision = '8a33708e30ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
