"""add blog markdown body

Revision ID: b7730ca2847e
Revises: 2caa26e98e36
Create Date: 2017-09-24 21:08:41.641902

"""

# revision identifiers, used by Alembic.
revision = 'b7730ca2847e'
down_revision = '2caa26e98e36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
